export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const UPDATE_MOVIES_FILTERS = "UPDATE_MOVIES_FILTERS";

export const FETCH_MOVIE_REQUEST = "FETCH_MOVIE_REQUEST";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE";


export const FETCH_SCREEN_MOVIE_REQUEST = "FETCH_SCREEN_MOVIE_REQUEST";
export const FETCH_SCREEN_MOVIE_SUCESS = "FETCH_SCREEN_MOVIE_SUCESS";
export const FETCH_SCREEN_MOVIE_FAILURE = "FETCH_SCREEN_MOVIE_FAILURE";