import Head from 'next/head'
import { Grid, GridItem, HStack, Show, Box, IconButton, Button } from '@chakra-ui/react'
import { ArrowLeftIcon, ArrowRightIcon } from "@chakra-ui/icons"
import { useCallback, useState } from 'react';
import { useDispatch, connect } from 'react-redux';
import NavBar from '../components/NavBar'
import MovieGrid from "../components/MovieGrid"
import MovieHeading from '../components/MovieHeading'
import GenreSelector from '@/components/genreSelector'
import SortSelector from '../components/SortSelector'
import { updateMoviesFilters, fetchMoviesRequest } from '../store/movies/actions';

function Home({ filters, nbPages }: any) {

  const [pages, setPages] = useState<number[]>([1, 2, 3])
  const [currentPage, setCurrentPage] = useState<number>(1)
  const dispatch = useDispatch()

  const handlePageChange = useCallback((page: number) => {
    dispatch(updateMoviesFilters("pageParam", page))
    dispatch(fetchMoviesRequest(filters))
    setCurrentPage(page)
    let pages = [1, 2, 3]
    if (page == nbPages)
      pages = [nbPages - 2, nbPages - 1, nbPages]
    if (page !== 1)
      pages = [page - 1, page, page + 1]
    setPages(pages)
  }, [])

  return (
    <>
      <Head>
        <title>Cinema App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <Grid templateAreas={{
        base: `"nav" "main" "pagination"`,
        lg: `"nav nav" "aside main"`
      }}

      >
        <GridItem area="main" >
          <Box paddingLeft={2}>
            <MovieHeading />
            <HStack spacing={5} paddingLeft={2} >
              <GenreSelector />
              <SortSelector />
            </HStack>
          </Box>
          <MovieGrid />
          <Box justifyContent="center">
            <IconButton aria-label='Search database' icon={<ArrowLeftIcon />} onClick={() => handlePageChange(1)} />
            {
              pages.map((index) =>
                <Button
                  bg={currentPage == index ? 'blue.700' : 'whiteAlpha.100'}
                  marginLeft={2}
                  key={index}
                  onClick={() => handlePageChange(index)}
                >
                  {index}
                </Button>
              )
            }
            <IconButton marginLeft={2} aria-label='Search database' icon={<ArrowRightIcon />} onClick={() => handlePageChange(nbPages)} />
          </Box>
        </GridItem>

      </Grid >
    </>
  )
}

const mapStateToProps = ({ moviesState }: any) => {
  return {
    filters: moviesState.filters,
    nbPages: moviesState.nbPages
  };
};

export default connect(mapStateToProps)(Home);
